### ISSUE TITLE
Use != null as default condition

### ISSUE THREAD

**Issue by MartinMystikJonas** [dermatthes/text-template#10]
It would improve radability of out templates if we can use just:
```
{if var}Var: {=var}{/if}
```
instead of:
```
{if var != null}Var: {=var}{/if}
```

**Comment by dermatthes** [comment]
In this case it should support `not` as well: {if !var}..{/if}

Can you provide PR for this?

**Comment by MartinMystikJonas** [comment]
I can try

**Comment by MartinMystikJonas** [comment]
see #12
