### ISSUE TITLE
Unexpected behaviuor of whitespace strippping

### ISSUE THREAD

**Issue by MartinMystikJonas** [dermatthes/text-template#11]
I just encountered quite unexpected bahaviour of whitespace stripping feature.

```
Header
{if var != null}{=var}{/if}
Footer
```

```
Header

{if var != null}{=var}{/if}
Footer
```

```
Header
{if var != null}
{=var}
{/if}
Footer
```

all results in:

```
HeaderVAR
Footer
```

instead of expected

```
Header
VAR
Footer
```

In fact I found no easy and obvious way to keep VAR on separete line.

Please let me know if you want any help with my requests. I could prepare PR if you want or at least test cases.

**Comment by dermatthes** [comment]
That would be great :)

**Comment by MartinMystikJonas** [comment]
Ok looks like I have made it :-) See #13
