### ISSUE TITLE
Skipped blocks leave empty lines

### ISSUE THREAD

**Issue by JohnDaniels02** [dermatthes/text-template#14]
Example:  
Given is an Array of Products which are parsed fine, but the skipped parts will lead to blank lines as in the following.  
*<TEXT>*Onlinebestellung
{for prod in products}
*<AP>*{= prod.sku},{= prod.quantity},{= prod.pifData.basePrice.price},,{= prod.itemName},,
{if prod.pifData.basePrice.price != 0}
{if prod.notice !=""}
*<AT>*{=prod.notice}
{/if}
{/if}
{if prod.pifData.basePrice.price == 0}
*<ANFRAGEPOSITION>*{= prod.sku},{= prod.quantity},,,{= prod.itemName},,
{if prod.notice !=""}
*<AT>*{=prod.notice}
{/if}
{/if}
{/for}
*<>*

Results in the following output:

*<TEXT>*Onlinebestellung

AP 129842,1,0.13,,LogiLink Audio Adapter 1x Mini 3,5mm -&gt; 2x Cinch St/Bu,,

AP  152578,1,0.13,,Herlitz Schnellhefter A4 PP f.sort transparenter Vordeckel,,

AP 161145,1,0.13,,Schwaiger F-Stecker 7,0mm Silber,,

<>

EDIT: Sadly most of the blank lines are stripped in the output of the Issue. There are 13 Blank lines between each AP

**Comment by dermatthes** [comment]
Might be a general issue about when to issue a newline and when not (if statements issued in the next line).
Please provide a PR.

**Comment by dermatthes** [comment]
Added default section {strip_empty_lines}{/stip_empty_lines}
