### ISSUE TITLE
Unable to detect usage of undefined variable

### ISSUE THREAD

**Issue by MartinMystikJonas** [dermatthes/text-template#9]
There is no way how to detect errors in template when undefined varibale is used. It is silently replaced by NULL.

**Comment by dermatthes** [comment]
This is the desired behavior.

You could use `{= __CONTEXT__ | raw}` to see the actual context. Or define a filter to throw an exception on null values. (e.g. `{= varname | notNull }`)

Does this work for you?

**Comment by dermatthes** [comment]
Seems to be a bug. _getValueByName() will throw an error if you pass an object but won't if you pass an array.

I changed this with the last commit. Can you verify its working as expected?

Maybe we could introduce a `ContextUndefinedException` (better name?) extending `TemplateParsingException`

**Comment by dermatthes** [comment]
Fixed softFail will allways be true...

**Comment by MartinMystikJonas** [comment]
It looks better now. I would suggest UnknownContextItemException(message, varName). Expection containing varName would be really useful in displaying what went wrong to user.

**Comment by dermatthes** [comment]
What's about `UndefinedVariableException`?

**Comment by dermatthes** [comment]
So far. I'll close this issue. Thank you for your help. :-)

**Comment by MartinMystikJonas** [comment]
Glad to help. Thank you for nice library ;-)
